namespace V.Script.Syntax;

public enum SyntaxKind
{
    None,
    EndOfFile,
    BadToken,

    // literals & names
    Identifier,
    IntLiteral,
    LongLiteral,
    UIntLiteral,
    ULongLiteral,
    DoubleLiteral,
    FloatLiteral,
    DecimalLiteral,
    StringLiteral,
    InterpolatedStringLiteral,
    CharLiteral,

    // punctuation
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    QuestionDot,
    Question,
    QuestionQuestion,
    QuestionQuestionEquals,
    Arrow,          // =>

    // operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    LessLess,
    GreaterGreater,
    LessLessEquals,
    GreaterGreaterEquals,
    Equals,
    EqualsEquals,
    BangEquals,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    PercentEquals,
    AmpEquals,
    PipeEquals,
    CaretEquals,
    PlusPlus,
    MinusMinus,

    // keywords
    TrueKeyword,
    FalseKeyword,
    NullKeyword,
    VarKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    DoKeyword,
    ForKeyword,
    ForeachKeyword,
    InKeyword,
    ReturnKeyword,
    BreakKeyword,
    ContinueKeyword,
    TryKeyword,
    CatchKeyword,
    FinallyKeyword,
    ThrowKeyword,
    NewKeyword,
    AwaitKeyword,
    IsKeyword,
    AsKeyword,
    TypeofKeyword,
    SwitchKeyword,
    CaseKeyword,
    DefaultKeyword,
}
